### ISSUE TITLE
[Feature Request] Add persistent cache to `session.load`

### ISSUE THREAD

**Issue by remorses** [modularml/max#166]
### What is your request?

I am interested in using Max to speed up boot times in platforms like Relicate and Fly.io, currently `session.load` seems to compile the model on every call, from the docs:

> The first time you load a model, it might take a few minutes to compile it, but this up-front cost will pay dividends in latency savings provided by our next-generation graph compiler.

It would be awesome if you can make this compilation output serializable so you can save it to disk and cache it. For example with `session.load(model, cache='./compiled_model')

This would mean you can create a Dockerfile with the model already compiled so it can boot very fast.

Even better if you make `load` able to use Direct Memory Access for weights that live on the GPU.

### What is your motivation for this change?

Making Max models boot fast would make Max the best way to deploy models in serverless GPU platforms like Replicate and Runpod. I am sure Max could skyrocket its adoption if boot times were good.

Current boot times on these platforms can take minutes.

**Comment by ehsanmok** [comment]
Thanks! we are going to enable storing a compiled model soon. But note that once a model is compiled for a target it cannot be used on a different target.

**Comment by BradLarson** [comment]
As an update to this issue, we should now have caching by default enabled for inference sessions starting with the 24.5 release and also in current nightlies. The model should be compiled on first run, then loaded from the local cache on subsequent runs. If this isn't happening, check for the presence of the `enable_model_ir_cache` variable in `~/.modular/modular.cfg` to make sure caching isn't somehow being disabled.

We have early experimental support in the nightlies for manual serialization of compiled models and loading rather than recompiling them in multiple runs, but the actual runtime performance isn't significantly different from the caching described above.
