### ISSUE TITLE
Is MAGIC for musl only?

### ISSUE THREAD

**Issue by jradxl** [modularml/max#240]
I hear about Magic, so I thought I'd try it.
Looking at the code of your curl installer, you limit the Linux version to musl
```
if [[ $PLATFORM == "Darwin" ]]; then
  PLATFORM="apple-darwin"
elif [[ $PLATFORM == "Linux" ]]; then
  PLATFORM="unknown-linux-musl"
elif [[ $(uname -o) == "Msys" ]]; then
  PLATFORM="pc-windows-msvc"
fi
```
But your installer doesn't warn me or refuse to install on my typical  AMD64 installation of Ubuntu

Linux desktop 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

I've tried to find a Magic/Mojo system requirements document, but haven't.
I would have thought you would have mentioned this restriction. At least prior to magic, mojo did install.
Comments?

**Comment by ehsanmok** [comment]
Thanks for the feedback! the system requirement is 8GB of RAM and magic should support major Linux distros including Ubuntu, MacOS and WSL2. Curious have you got any error when installing magic and then MAX/Mojo or it worked for our out of the box?

**Comment by jradxl** [comment]
Magic installs but only --version and --help menu options work. All others hang indefinitely.
Pipx works fine.
I've tested both Magic and Pixi in new, separate user accounts so as not to interfere with my normal account.

Your curl installer uses this URL
`https://dl.modular.com/public/magic/raw/versions/latest/magic-x86_64-unknown-linux-musl
`
So I would not expect a MUSL version to work on my standard Ubuntu kUbuntu 24.05

```
$ ldd --version ldd
ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35


```

**Comment by zbowling** [comment]
Hi there! The build name is named musl because we statically link against musl libc into the binary to avoid compatibility issues with different distro glibc versions so that the binary is portable to nearly all distros regardless of the libc (so basically all we require is a modern enough Linux kernel with syscalls available for the last 8 years). It has no relation to the glibc or musl libc on your system so it should work. 

For why it's hanging, I'm not sure. Which commands are invoking where it hangs? 

Also can you run `magic info` and `lsb_release -a` and post here?
